### ISSUE TITLE
Rename project to k4ever-backend?

### ISSUE THREAD

**Issue by markusressel** [freitagsrunde/k4ever-backend#1]
Imho the name "api" is a little misleading, as this project is supposed to not only be an interface for clients, but also the implementation of business logic like persistence, user management, product management etc. An "api" project would mean to me that it only exposes some kind of service to the public.

A strict seperation into k4ever-api (for the rest server part) and k4ever-backend (for the business logic part) would be optimal but as this would probably only cause a lot of headache when developing and bring no real additional value (despite the more enforced seperation of concerns) renaming the project to a more general name like "backend" or something similar would be my preferred solution.

**Comment by ekeih** [comment]
Renaming sounds good to me. :+1:

**Comment by markusressel** [comment]
Done.
