### ISSUE TITLE
Endpoint `/api/v1/users/{id}/` does not work

### ISSUE THREAD

**Issue by zergar** [freitagsrunde/k4ever-backend#10]
`/api/v1/users/{id}/` always returns

```json
{
    "error": "User not found"
}
```

even if the user does in fact exist.

**Comment by phiphi282** [comment]
This is an artifacts from trying to change to usernames from ids for the user related endpoints.

This will be changed shortly, as soon as using usernames is implemented (see #7 because of too many changes in this pr already ^^')
