### ISSUE TITLE
As a product manager, I want to be able to disable currently not avialble Products.

### ISSUE THREAD

**Issue by zergar** [freitagsrunde/k4ever-backend#22]
A product manager should be able to disable currently unused products to prevent confusion about which products are available for purchase.

A disabled Product should not be able to purchase and / or appear on the response of the `/products/`-endpoint. If only the first variant is to be implemented every product should consist of an additional field which represents the disabled-status of the product like a flag.

**Comment by phiphi282** [comment]
@zergar do you want to have an extra endpoint for disabling products or are you OK with doing that in the PUT products endpoint?
