### ISSUE TITLE
When creating an User via `POST /users/` I'm unable to log in with that user

### ISSUE THREAD

**Issue by zergar** [freitagsrunde/k4ever-backend#24]
When creating an User via `POST /users/` I'm unable to log in with that user.

## Steps to Reproduce:
1. Send `{"name": "moi", "display_name": "MOI", "password": "moi"}` to `POST /users/`
2. Try logging in with `{"name": "moi", "password": "moi"}` to `POST /login/`
3. Get error `{"code": 401, "message": "crypto/bcrypt: hashedPassword is not the hash of the given password"}`

**Comment by phiphi282** [comment]
I found the error in my code.
When creating a user with a POST request if don't add the password to the user (stupid me).

Fortunately, his can be easily fixed.
