### ISSUE TITLE
Adding another docker-compose-script for allowing other developers to easily build any commit by themselves

### ISSUE THREAD

**Issue by zergar** [freitagsrunde/k4ever-backend#29]
It would be nice to be able to dockerize any commit with a docker-compose-script. It might be necessary to add a new endpoint `GET /version/` for being able to identify the currently running api. 

I suggest the following response structure for this endpoint:
```json
{
    "version": "String",
    "branch": "String",
    "commit": "String"
}
```

The values of these variables can be set by environment variables on building the application.

**Comment by phiphi282** [comment]
We do have a docker-compose.build.yml file now with which you can build the image yourself.
