### ISSUE TITLE
Add datetime purchased at to every purchase when performing `GET /users/:user/purchases/` 

### ISSUE THREAD

**Issue by zergar** [freitagsrunde/k4ever-backend#34]
Add datetime purchased at to every purchase when performing `GET /users/:user/purchases/`. This way, the purchases can be ordered and the datetime of a purchase can be shown to an user.

**Comment by phiphi282** [comment]
@zergar What exactly do you mean with datetimes at purchase?
We already have datetimes for created and last_modified, that are being shown in the purchases endpoint.

If you need other datetimes please let us know :smile:
