### ISSUE TITLE
Add endpoint for fetching own user Information 

### ISSUE THREAD

**Issue by zergar** [freitagsrunde/k4ever-backend#9]
I want to get my own user information without needing to parse the JWT-string first.

**Comment by phiphi282** [comment]
@zergar do you have an idea to what the endpoints path should look like?

**Comment by phiphi282** [comment]
It should be noted here, that you can always extract your username from the jwt and get your user information via the /users/{username}/ endpoint.

**Comment by zergar** [comment]
I think the best way would be to include this information in the response on login. This way it wouldn't be necessary to parse the JWT-String which produces some quite ugly code and facilitates quirks.

**Comment by phiphi282** [comment]
> I think the best way would be to include this information in the response on login. This way it wouldn't be necessary to parse the JWT-String which produces some quite ugly code and facilitates quirks.

Well, since you now the username yourself already when logging in you can just use that when you get the jwt.
This way you now that you have the correct username and the api doesn't need to send back part of the same data you provided.
